from .animal import Animal
from .anaconda import Anaconda
from .boaconstrictor import BoaConstrictor
from .clownfish import Clownfish
from .dolphin import Dolphin
from .donkey import Donkey
from .gartersnake import GarterSnake
from .goat import Goat
from .goldfish import Goldfish
from .horse import Horse
from .kingsnake import KingSnake
from .llama import Llama
from .pig import Pig
from .python import Python
from .seahorse import Seahorse
from .turtle import Turtle
